spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        binder:
          brokers: localhost:9092
      bindings:
        producer-out-0:
          destination: test-topic
          producer:
            useNativeEncoding: true
        consumer-in-0:
          destination: test-topic
          consumer:
            use-native-decoding: true